apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-airflow-logs
  namespace: airflow
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.airflow.svc.cluster.local
    path: "/exports/logs"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-airflow-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-airflow-dags
  namespace: airflow
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.airflow.svc.cluster.local
    path: "/exports/dags"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-airflow-dags
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
